workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    working_directory: spa

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default

    scripts:
      - name: Install deps
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Build IPA (App Store automatic signing)
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa
