workflows:
  ios-release:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    working_directory: spa

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials
      vars:
        BUNDLE_ID: com.prirodaspa.app

    scripts:
      - name: Install dependencies
        script: flutter pub get

      - name: Install pods
        script: |
          cd ios
          pod install

      - name: Build IPA
        script: |
          flutter build ipa --release \
            --export-options-plist=export_options.plist

    artifacts:
      - build/ios/ipa/*.ipa

    code_signing:
      app_store_connect: true
      bundle_identifier: com.prirodaspa.app
      signing_type: app-store
