workflows:
  ios-release:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    working_directory: spa

    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - app_store_credentials   # Тут лежит твой API key
      vars:
        BUNDLE_ID: com.prirodaspa.app

    scripts:
      - name: Install Flutter dependencies
        script: |
          flutter pub get

      - name: Install CocoaPods
        script: |
          cd ios
          pod install

      - name: Build iOS release IPA
        script: |
          flutter build ipa --release
          echo "IPA build complete"

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true

      # Автоматическая загрузка в TestFlight (опционально)
      # app_store_connect:
      #   auth:
      #     issuer_id: $APP_STORE_ISSUER_ID
      #     key_id: $APP_STORE_KEY_ID
      #     key: $APP_STORE_PRIVATE_KEY
      #   submit_to_testflight: true
      #   beta_groups:
      #     - Internal Testing
